---
version: 0.2


env:
  parameter-store:
    JWT_SECRET: JWT_SECRET

phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get install software-properties-common
      - lsb_release -a
      - uname -r
      - apt-get update && apt-get -y install jq
      - wget https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz
      - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev  libncursesw5-dev xz-utils tk-dev
      - tar xvf Python-3.6.7.tgz
      - pwd
      - cd Python-3.6.7/
      - ./configure --enable-optimizations --with-ensurepip=install
      - make altinstall
      - python3.6 -V
      - which python3.6
      - ls /usr/bin/python*
      - update-alternatives --install /usr/bin/python python /usr/bin/python3.4 1
      - update-alternatives --install /usr/bin/python python /usr/local/bin/python3.6 2
      - pip3.6 install --upgrade awscli
      - pip3.6 install --upgrade pip
      - cd -
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' simple_jwt_api.yml
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config
        - pip3.6 install -r requirements.txt
        - pip3.6 install typing
        - pip3.6 install pytest
        - python3.6 test_main.py
  build:
    commands:
        - docker build --tag $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - cat simple_jwt_api.yml
      - kubectl config view
      - aws sts get-caller-identity
      - kubectl apply -f simple_jwt_api.yml
      - printf '[{"name":"simple_jwt_api","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
      - pwd
      - ls
artifacts:
  files: build.json
